### ISSUE TITLE
References Missing & Potentially Incorrect Formula to Calculate MAGE

### ISSUE THREAD

**Issue by Nathaniel-Fernandes** [brinnaebent/cgmquantify#4]
Thank you for this package! I encountered two issues.

1. I can't seem to find the references on the page where you give to formulas for each metric: [https://github.com/brinnaebent/cgmquantify/blob/master/paper.md](https://github.com/brinnaebent/cgmquantify/blob/master/paper.md). Maybe it was deleted accidentally?

2.  I believe the formula used to calculate MAGE is inaccurate. You give ``` mean glucose outside +- x SD of mean```. Which paper is this from? I read the Rawlings:2011; Kovatchev:2019; ADA:2018; and Service 2013 papers and all seem to say ``` mage = mean( AGE ) ``` where AGE is the amplitudes from peak to nadir (or vice versa) that are > 1 SD.

If there is a paper that calculates MAGE using the formula in the package, PLEAAAAAASSSSEEEE send me the link or doi!! I need it for a paper I'm writing.

**Comment by brinnaebent** [comment]
Hi Nathaniel,
Thanks for opening an issue.
1. the paper.bib file in the main repository has all of the references.
2. Unfortunate wording, this should be MAGEx, which is the preliminary calculation prior to implementing the full MAGE calculation. We have implemented the full MAGE calculation using Baghurst's algorithm locally but have not yet updated the cgmquantify package with this code. This package is still under development, so please check back in for the full MAGE calculation. Thank you for noting that this naming convention may be misleading. 

Best of luck with your paper. If you use this package, please cite our recent publication with the package: https://www.cambridge.org/core/journals/journal-of-clinical-and-translational-science/article/digital-biomarker-discovery-pipeline-an-open-source-software-platform-for-the-development-of-digital-biomarkers-using-mhealth-and-wearables-data/A6696CEF138247077B470F4800090E63

**Comment by brinnaebent** [comment]
@Nathaniel-Fernandes I'll try to post an update with the MAGE calculation by the end of the day tomorrow. I will tag you when I update.

**Comment by brinnaebent** [comment]
Hi @Nathaniel-Fernandes , you should be able to install the new cgmquantify package with the full MAGE calculation. The previous MAGEx calculation is now called "MGE" to reduce confusion. I have also updated the User Guide and documentation with the new terms. Thanks for posting the issue and best of luck with your project!

**Comment by Nathaniel-Fernandes** [comment]
Thank you so much for your quick fix!
